name: Busted
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit Tests
        uses: lunarmodules/busted@v2.2.0
        with:
            args: --directory=lua ./nvim-highlight-colors/
